proxy:
    image: main
    restart: unless-stopped
    depends_on:
      - postgres
    command: bash -c "sh /proj/bin/main --listen-addr :8080 --db-host localhost --db-port 5432 --db-user postgres --db-pass changeit --db-name main"

  postgres:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeit
      POSTGRES_DB: main
    volumes:
      - pgdata:/var/lib/postgresql/data
